# Generated by Django 4.0.5 on 2022-06-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team/')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('mission', models.CharField(max_length=100)),
                ('vision', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('content1', models.TextField(max_length=100)),
                ('content2', models.TextField(max_length=100)),
                ('content3', models.TextField(max_length=100)),
            ],
        ),
    ]
