# Generated by Django 4.0.5 on 2022-06-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammodel',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='teammodel',
            name='value',
        ),
        migrations.RemoveField(
            model_name='teammodel',
            name='vision',
        ),
    ]
