# Generated by Django 4.0.5 on 2022-06-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='crated_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='full_name',
            field=models.CharField(default=2, max_length=222),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
