# Generated by Django 4.0.5 on 2022-06-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment_crated_at_comment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
    ]
